SRC += logo.c
OLED_DRIVER_ENABLE = yes
DYNAMIC_KEYMAP_LAYER_COUNT = 6
MOUSEKEY_ENABLE = yes
UNICODE_ENABLE = no
SEND_STRING_ENABLE = yes
VIA_ENABLE = no

# CONSOLE_ENABLE = yes
# COMMAND_ENABLE = no
# UNICODE_ENABLE = yes

#VIA_ENABLE = yes